openapi: 3.0.2
info:
  title: FastAPI
  version: 0.1.0
paths:
  /api/working-hours/syncore/{aggregation}/{start_date}/{end_date}:
    get:
      tags:
        - Syncore API
      summary: Syncore Records Daterange
      operationId: syncore_records_daterange_api_working_hours_syncore__aggregation___start_date___end_date__get
      parameters:
        - required: true
          schema:
            $ref: '#/components/schemas/AggregationChoices'
          name: aggregation
          in: path
        - required: true
          schema:
            title: Start Date
            type: string
            format: date
          name: start_date
          in: path
        - required: true
          schema:
            title: End Date
            type: string
            format: date
          name: end_date
          in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Syncore Records Daterange Api Working Hours Syncore  Aggregation   Start Date   End Date  Get
                type: array
                items:
                  $ref: '#/components/schemas/SyncoreRecord'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/working-hours/syncore/{aggregation}/{start_date}:
    get:
      tags:
        - Syncore API
      summary: Syncore Records Startdate
      operationId: syncore_records_startdate_api_working_hours_syncore__aggregation___start_date__get
      parameters:
        - required: true
          schema:
            $ref: '#/components/schemas/AggregationChoices'
          name: aggregation
          in: path
        - required: true
          schema:
            title: Start Date
            type: string
            format: date
          name: start_date
          in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Syncore Records Startdate Api Working Hours Syncore  Aggregation   Start Date  Get
                type: array
                items:
                  $ref: '#/components/schemas/SyncoreRecord'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/working-hours/timesheet/{aggregation}/{start_date}:
    get:
      tags:
        - SAP Timesheet API
      summary: Timesheet Records Startdate
      operationId: timesheet_records_startdate_api_working_hours_timesheet__aggregation___start_date__get
      parameters:
        - required: true
          schema:
            $ref: '#/components/schemas/AggregationChoices'
          name: aggregation
          in: path
        - required: true
          schema:
            title: Start Date
            type: string
            format: date
          name: start_date
          in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Timesheet Records Startdate Api Working Hours Timesheet  Aggregation   Start Date  Get
                type: array
                items:
                  $ref: '#/components/schemas/TimesheetRecord'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/working-hours/timesheet/{aggregation}/{start_date}/{end_date}:
    get:
      tags:
        - SAP Timesheet API
      summary: Timesheet Records Startdate
      operationId: timesheet_records_startdate_api_working_hours_timesheet__aggregation___start_date___end_date__get
      parameters:
        - required: true
          schema:
            $ref: '#/components/schemas/AggregationChoices'
          name: aggregation
          in: path
        - required: true
          schema:
            title: Start Date
            type: string
            format: date
          name: start_date
          in: path
        - required: true
          schema:
            title: End Date
            type: string
            format: date
          name: end_date
          in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Timesheet Records Startdate Api Working Hours Timesheet  Aggregation   Start Date   End Date  Get
                type: array
                items:
                  $ref: '#/components/schemas/TimesheetRecord'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    AggregationChoices:
      title: AggregationChoices
      enum:
        - DAILY
        - WEEKLY
      type: string
      description: An enumeration.
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    SyncoreRecord:
      title: SyncoreRecord
      required:
        - date
        - expected_hours
      type: object
      properties:
        last_name:
          title: Last Name
          type: string
        first_name:
          title: First Name
          type: string
        mail:
          title: Mail
          type: string
        date:
          title: Date
          type: string
          format: date
        day_of_week:
          title: Day Of Week
          type: string
        week_of_year:
          title: Week Of Year
          type: string
        expected_hours:
          title: Expected Hours
          type: number
    TimesheetRecord:
      title: TimesheetRecord
      required:
        - sap_employee_id
        - date
        - recorded_hours
      type: object
      properties:
        last_name:
          title: Last Name
          type: string
        first_name:
          title: First Name
          type: string
        mail:
          title: Mail
          type: string
        sap_employee_id:
          title: Sap Employee Id
          type: string
        date:
          title: Date
          type: string
          format: date
        company_code:
          title: Company Code
          type: string
        network:
          title: Network
          type: string
        receiver_order:
          title: Receiver Order
          type: string
        receiver_costcenter:
          title: Receiver Costcenter
          type: string
        activity:
          title: Activity
          type: string
        recorded_hours:
          title: Recorded Hours
          type: number
        activity_type:
          title: Activity Type
          type: integer
        timesheet_record:
          title: Timesheet Record
          type: string
        attendance_absence_type:
          title: Attendance Absence Type
          type: integer
    ValidationError:
      title: ValidationError
      required:
        - loc
        - msg
        - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
              - type: string
              - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
